name: Terraform Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Prepare Files
        run: ./prepare_files.sh

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan \
          -var="client_id=${{ env.ARM_CLIENT_ID }}" \
          -var="client_secret=${{ env.ARM_CLIENT_SECRET }}" \
          -var="tenant_id=${{ env.ARM_TENANT_ID }}" \
          -var="subscription_id=${{ env.ARM_SUBSCRIPTION_ID }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve \
          -var="client_id=${{ env.ARM_CLIENT_ID }}" \
          -var="client_secret=${{ env.ARM_CLIENT_SECRET }}" \
          -var="tenant_id=${{ env.ARM_TENANT_ID }}" \
          -var="subscription_id=${{ env.ARM_SUBSCRIPTION_ID }}"
